# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books2_app', '0002_auto_20170621_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='name',
        ),
    ]
